///********************************************************************************************************************************
///The code on this page is generated by the code generator, do not manually modify.
///CodeGenerator: Megumin.CSCodeGenerator.  Version: 1.0.1
///CodeGenericBy: Megumin.AI.BehaviorTree.Editor.NodeGenerator
///CodeGenericSourceFilePath: Assets/Samples/BehaviorTree/InterfaceNode/AnimalGenerator.asset
///********************************************************************************************************************************

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.AI.BehaviorTree
{
    [DisplayName("IAnimal_Wow")]
    [Category("IAnimal")]
    [AddComponentMenu("Wow")]
    public sealed class IAnimal_Wow_Node : BTActionNode<IAnimal>
    {
        protected override Status OnTick(BTNode from, object options = null)
        {
            ((IAnimal)MyAgent).Wow();
            return Status.Succeeded;
        }
    }
}




